version: "3.8"
services:
  backend:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - test
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: shipping
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    # volumes:
      # - db-data:/var/lib/mysql
    networks:
      - test
networks:
  test:
volumes:
  db-data:
  test-db-data:
